### ISSUE TITLE
Consider running automated tests on Windows and mac

### ISSUE THREAD

**Issue by johnbradley** [Imageomics/Andromeda#16]
See https://github.com/Imageomics/Andromeda/pull/14#discussion_r1172642002

**Comment by johnbradley** [comment]
My only concern with this is not running over in the number of minutes we are allocated. For Windows github actions use 2x minutes and mac uses 10x minutes: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers

Here is some documentation on minutes allocated for various plans:
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes

**Comment by thompsonmj** [comment]
It seems tests should reflect the intended use-case then. If it's something a user will run on their system, Windows/Ubuntu/macOS tests would be good. But for web app to be hosted on Linux, probably not needed. Our org has 3000 monthly Actions minutes available.

**Comment by hlapp** [comment]
I'm skeptical there's a well motivated use-case supporting a requirement to run and pass tests on Window and macOS. I'm not seeing how running on a local machine can't and in fact shouldn't be solved through using Docker containers instead.

I'm going to close this, but if anyone feels they a strong counterargument feel free to object or re-open.
