### ISSUE TITLE
Improve land cover big and small column documentation

### ISSUE THREAD

**Issue by johnbradley** [Imageomics/Andromeda#71]
The sizes of the big and small land cover regions are not well documented.
See https://github.com/Imageomics/Andromeda/pull/65#issuecomment-1769325708 for more.

**Comment by egrace479** [comment]
I think it's resolved. The note about documentation within the docs has been made in #73 regarding the wiki, so I believe it can be closed.

**Comment by thompsonmj** [comment]
Yep, looks good!
